name: ahsd
channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - pytorch
  - torchvision
  - torchaudio
  - astropy
  - healpy
  - gwpy
  - pycbc
  - bilby
  - emcee
  - dynesty
  - arviz
  - h5py
  - jupyterlab
  - ipython
  - ipywidgets
  - pip
  - pip:
      - transformers
      - wandb
      - seaborn
      - xgboost
      - nflows